// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU2Nw36iQgfj6_rxN82qLzMrT6533yOrE',
    appId: '1:532130613023:android:8b7dc64d13a076e4fd922a',
    messagingSenderId: '532130613023',
    projectId: 'project1-8cafd',
    storageBucket: 'project1-8cafd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZgFDHRJin6IdEJXiEMesocP0JWKbuyZE',
    appId: '1:532130613023:ios:692697c89141df12fd922a',
    messagingSenderId: '532130613023',
    projectId: 'project1-8cafd',
    storageBucket: 'project1-8cafd.appspot.com',
    iosBundleId: 'com.rideNow.rideNow',
  );
}
