
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution  do
      sh "flutter clean"
      sh "flutter build apk --flavor development --target lib/main_dev.dart --split-per-abi --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:532130613023:android:8b7dc64d13a076e4fd922a",
      firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
      groups: "bmennarefaat84@gmail.com",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release-arm64-v8a.apk",
      android_artifact_type: "APK",
      release_notes: "Version 1.0.0",
      upload_timeout: 1800
    )
  end
end
